# 2025-01-02 // maxylan@torpssons.se
networks:
  magenet:
    driver: bridge
  mage-inet:
    driver: none

volumes:
  mage.db_data:
  mage.ollama_data:

services:
  mage.storage: # Postgresql Database
    container_name: "${STORAGE_NAME}"
    restart: unless-stopped
    image: postgres:17.2
    command: [ "-p", "${STORAGE_PORT}" ]
    volumes:
      - "${STORAGE_MOUNT_POINT}/init:/docker-entrypoint-initdb.d"
      - "mage.db_data:/${STORAGE_VOLUME_TARGET}"
    environment:
      APP_NAME: "${APP_NAME}"
      APP_VERSION: "${GUARD_VERSION}.${GARDEN_VERSION}.${RECEPTION_VERSION}.${STORAGE_VERSION}"
      STORAGE_NAME: "${STORAGE_NAME}"
      STORAGE_VERSION: "${STORAGE_VERSION}"
      STORAGE_ENVIRONMENT: "${STORAGE_ENVIRONMENT}"
      PGTZ: "Europe/Stockholm"
      TZ: "Europe/Stockholm"
    env_file:
      - "${STORAGE_CONFIGURATION_FILE}"
    networks:
      - magenet
    expose:
      - "${STORAGE_PORT}"
    ports:
      - "${STORAGE_PORT}"

  mage.window: # Postgresql Database UI for the browser
    container_name: "${WINDOW_NAME}"
    restart: unless-stopped
    image: adminer:latest
    environment:
      APP_NAME: "${APP_NAME}"
      APP_VERSION: "${GUARD_VERSION}.${GARDEN_VERSION}.${RECEPTION_VERSION}.${STORAGE_VERSION}"
      ADMINER_PLUGINS: "tables-filter tinymce"
      ADMINER_DEFAULT_SERVER: "${STORAGE_NAME}:${STORAGE_PORT}"
      ADMINER_DEFAULT_DB_DRIVER: "pgsql"
      ADMINER_PORT: "${WINDOW_PORT}"
      PGTZ: "Europe/Stockholm"
      TZ: "Europe/Stockholm"
    networks:
      - magenet
    ports:
      - "${WINDOW_PORT}"
      - "8080"

  mage.secretary: # ollama
    container_name: "${SECRETARY_NAME}"
    restart: unless-stopped
    image: ollama/ollama:latest
    # command: [ "serve", "deepseek-r1" ]
    # command: [ "serve", "&&", "create", "mario", "-f", "/root/Modelfile" ]
    command: [ "serve" ]
    volumes:
      - "${SECRETARY_MOUNT_POINT}/Modelfile:/root/Modelfile"
      - "mage.ollama_data:/root/.ollama"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
    environment:
      APP_NAME: "${APP_NAME}"
      APP_VERSION: "${GUARD_VERSION}.${GARDEN_VERSION}.${RECEPTION_VERSION}.${STORAGE_VERSION}"
      SECRETARY_NAME: "${SECRETARY_NAME}"
      OLLAMA_TIMEOUT: 30
    env_file:
      - "${STORAGE_CONFIGURATION_FILE}"
    networks:
      - magenet
      # - mage-inet
    expose:
      - "11434"

  mage.reception: # ASP.NET 9.0 Backend
    container_name: "${RECEPTION_NAME}"
    restart: unless-stopped
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: "${RECEPTION_VOLUME_TARGET}"
    command: [ "dotnet", "run", "-c", "Debug" ]
    volumes:
      - "${RECEPTION_MOUNT_POINT}:${RECEPTION_VOLUME_TARGET}"
    environment:
      APP_NAME: "${APP_NAME}"
      APP_VERSION: "${GUARD_VERSION}.${GARDEN_VERSION}.${RECEPTION_VERSION}.${STORAGE_VERSION}"
      RECEPTION_NAME: "${RECEPTION_NAME}"
      RECEPTION_VERSION: "${RECEPTION_VERSION}"
      RECEPTION_BASE_PATH: "${RECEPTION_BASE_PATH}"
      RECEPTION_ENVIRONMENT: "${RECEPTION_ENVIRONMENT}"
      ASPNETCORE_ENVIRONMENT: "${RECEPTION_ENVIRONMENT}"
      RECEPTION_BLOB_STORAGE_FOLDER: "${RECEPTION_BLOB_STORAGE_FOLDER}"
      RECEPTION_BLOB_STORAGE: "${RECEPTION_VOLUME_TARGET}/${RECEPTION_BLOB_STORAGE_FOLDER}"
      RECEPTION_URL: "http://${RECEPTION_NAME}:${RECEPTION_PORT}"
      SECRETARY_BASE_PATH: "${SECRETARY_BASE_PATH}"
      SECRETARY_URL: "http://${SECRETARY_NAME}:${SECRETARY_PORT}"
      GARDEN_URL: "http://${GARDEN_NAME}:${GARDEN_PORT}"
      GUARD_URL: "http://${GUARD_NAME}:${GUARD_PORT}"
      STORAGE_URL: "${STORAGE_NAME}:${STORAGE_PORT}"
      HTTP_PORTS: "${RECEPTION_PORT}"
    env_file:
      - "${STORAGE_CONFIGURATION_FILE}"
    networks:
      - magenet
    expose:
      - "${RECEPTION_PORT}"
    ports:
      - "${RECEPTION_PORT}"

  mage.garden: # Angular 2 Frontend (Apache2 / httpd)
    container_name: "${GARDEN_NAME}"
    restart: unless-stopped # image: httpd:2.4-alpine
    build: ${GARDEN_MOUNT_POINT}
    working_dir: "${GARDEN_VOLUME_TARGET}"
    command: [ "apachectl", "-D", "FOREGROUND" ]
    volumes:
      - "${GARDEN_MOUNT_POINT}/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "${GARDEN_MOUNT_POINT}/mage.conf:/usr/local/apache2/conf/extra/mage.conf"
      - "${GARDEN_MOUNT_POINT}/dist/garden:${GARDEN_VOLUME_TARGET}"
    environment:
      APP_NAME: "${APP_NAME}"
      APP_VERSION: "${GUARD_VERSION}.${GARDEN_VERSION}.${RECEPTION_VERSION}.${STORAGE_VERSION}"
      GARDEN_NAME: "${GARDEN_NAME}"
      GARDEN_VERSION: "${GARDEN_VERSION}"
      GARDEN_ENVIRONMENT: "${GARDEN_ENVIRONMENT}"
      RECEPTION_URL: "http://${RECEPTION_NAME}:${RECEPTION_PORT}"
      GARDEN_URL: "http://${GARDEN_NAME}:${GARDEN_PORT}"
      GUARD_URL: "http://${GUARD_NAME}:${GUARD_PORT}"
      GARDEN_PORT: "${GARDEN_PORT}"
      APACHE_LOG_DIR: "/var/log/apache2/mage"
    networks:
      - magenet
    expose:
      - "${GARDEN_PORT}"

  mage.gate: # Angular 2 Frontend (Apache2 / httpd)
    container_name: "${GUARD_NAME}"
    restart: unless-stopped
    build: ${GUARD_MOUNT_POINT} # image: httpd:2.4-alpine
    working_dir: "${GUARD_VOLUME_TARGET}"
    command: [ "apachectl", "-D", "FOREGROUND" ]
    volumes:
      - "${GUARD_MOUNT_POINT}/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "${GUARD_MOUNT_POINT}/mage.conf:/usr/local/apache2/conf/extra/mage.conf"
      - "${GUARD_MOUNT_POINT}/dist/guard:${GUARD_VOLUME_TARGET}"
    environment:
      APP_NAME: "${APP_NAME}"
      APP_VERSION: "${GUARD_VERSION}.${GARDEN_VERSION}.${RECEPTION_VERSION}.${STORAGE_VERSION}"
      WINDOW_PORT: "${WINDOW_PORT}"
      WINDOW_BASE_PATH: "${WINDOW_BASE_PATH}"
      WINDOW_URL: "http://${WINDOW_NAME}:8080"
      RECEPTION_PORT: "${RECEPTION_PORT}"
      RECEPTION_BASE_PATH: "${RECEPTION_BASE_PATH}"
      RECEPTION_URL: "http://${RECEPTION_NAME}:${RECEPTION_PORT}"
      GARDEN_PORT: "${GARDEN_PORT}"
      GARDEN_BASE_PATH: "${GARDEN_BASE_PATH}"
      GARDEN_URL: "http://${GARDEN_NAME}:${GARDEN_PORT}"
      SECRETARY_PORT: "${SECRETARY_PORT}"
      SECRETARY_BASE_PATH: "${SECRETARY_BASE_PATH}"
      SECRETARY_URL: "http://${SECRETARY_NAME}:${SECRETARY_PORT}"
      GUARD_NAME: "${GUARD_NAME}"
      GUARD_PORT: "${GUARD_PORT}"
      GUARD_VERSION: "${GUARD_VERSION}"
      GUARD_BASE_PATH: "${GUARD_BASE_PATH}"
      GUARD_URL: "http://${GUARD_NAME}:${GUARD_PORT}"
      GUARD_ENVIRONMENT: "${GUARD_ENVIRONMENT}"
      APACHE_LOG_DIR: "/var/log/apache2/mage"
    networks:
      - magenet
    expose:
      - "${GUARD_PORT}"
    ports:
      - "80:${GUARD_PORT}"
